<a href="https://colab.research.google.com/github/Esteban-Caldera/ROBOTICA-2025/blob/main/U2A1.%20PROBLEMAARIO.%20Operaciones%20matriciales%20y%20vectoriales/PROBLEMARIO_Operaciones_matriciales_y_vectoriales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#U2A1.PROBLEMARIO. Operaciones matriciales y vectoriales
En esencia, esta tarea consistió en resolver problemas fundamentales de álgebra lineal utilizando Python como herramienta de cálculo. En lugar de hacer las operaciones a mano, se programaron las soluciones para que la computadora las ejecutara de forma rápida y precisa.

##Librerias

In [1]:
# Importamos la librería NumPy, que es el estándar en Python para trabajar con matrices y vectores.
# La renombramos como 'np' por convención para que sea más fácil de usar.
import numpy as np

# Importamos la clase 'Matrix' de la librería SymPy.
# SymPy es una librería para matemáticas simbólicas, ideal para encontrar el espacio nulo de forma exacta.
from sympy import Matrix

##Ejercicio 1: Suma de matrices

In [13]:
# --- Definición de las matrices ---
# Creamos la matriz A utilizando la función array de NumPy.
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [7, 9, 11]])

# Creamos la matriz B de la misma manera.
B = np.array([[12, 10, 8],
              [6, 4, 2],
              [0, -2, -4]])

# --- Operación de suma ---
# En NumPy, la suma de matrices se realiza de forma intuitiva con el operador '+'.
# NumPy se encarga de sumar cada elemento de A con su correspondiente en B.
C = A + B

# --- Impresión de resultados ---
# Mostramos las matrices originales y la resultante para una clara visualización.
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatriz Resultante C = A + B:")
print(C)

Matriz A:
[[ 2  4  6]
 [ 1  3  5]
 [ 7  9 11]]

Matriz B:
[[12 10  8]
 [ 6  4  2]
 [ 0 -2 -4]]

Matriz Resultante C = A + B:
[[14 14 14]
 [ 7  7  7]
 [ 7  7  7]]


##Ejercicio 2: Multiplicación de matrices

In [15]:
# --- Definición de las matrices ---
# Definimos la matriz A (dimensiones 3x2).
A = np.array([[2, 1],
              [3, 4],
              [5, 6]])

# Definimos la matriz B (dimensiones 2x2).
# El número de columnas de A (2) es igual al número de filas de B (2), por lo que la multiplicación es posible.
B = np.array([[7, 8],
              [9, 10]])

# --- Operación de multiplicación ---
# El operador '@' se utiliza en Python (a partir de la versión 3.5) específicamente para la multiplicación de matrices.
# Realiza el producto punto entre las filas de A y las columnas de B.
C = A @ B

# --- Impresión de resultados ---
print("Matriz A (3x2):")
print(A)
print("\nMatriz B (2x2):")
print(B)
print("\nMatriz Resultante C = A * B (3x2):")
print(C)

Matriz A (3x2):
[[2 1]
 [3 4]
 [5 6]]

Matriz B (2x2):
[[ 7  8]
 [ 9 10]]

Matriz Resultante C = A * B (3x2):
[[ 23  26]
 [ 57  64]
 [ 89 100]]


##Ejercicio 3: Inversión de matriz

In [14]:
# --- Definición de la matriz ---
# Definimos una matriz cuadrada A (3x3), requisito indispensable para que pueda tener inversa.
A = np.array([[4, 7, 2],
              [2, 6, 8],
              [3, 1, 9]])

# --- Cálculo de la inversa ---
# Usamos el módulo de álgebra lineal de NumPy (linalg) y su función inv() para calcular la inversa.
# Si la matriz no fuera invertible (su determinante es cero), este comando arrojaría un error.
A_inversa = np.linalg.inv(A)

# --- Impresión de resultados ---
print("Matriz A:")
print(A)
print("\nMatriz Inversa A^(-1):")
print(A_inversa)

Matriz A:
[[4 7 2]
 [2 6 8]
 [3 1 9]]

Matriz Inversa A^(-1):
[[ 0.2371134  -0.31443299  0.22680412]
 [ 0.03092784  0.15463918 -0.1443299 ]
 [-0.08247423  0.08762887  0.05154639]]


##Ejercicio 4: Resolución de sistema de ecuaciones lineales

In [16]:
# --- Representación matricial del sistema ---
# 2x + y + z = 8
# 3x + 5y + 2z = 21
# x + 2y + 4z = 11

# Matriz A: Contiene los coeficientes de las variables (x, y, z) en cada ecuación.
A = np.array([[2, 1, 1],
              [3, 5, 2],
              [1, 2, 4]])

# Vector B: Contiene los términos constantes (los resultados de cada ecuación).
B = np.array([8, 21, 11])

# --- Resolución del sistema ---
# La función np.linalg.solve(A, B) es el método preferido para resolver sistemas AX = B.
# Es numéricamente más estable y eficiente que calcular la inversa de A y multiplicarla por B.
X = np.linalg.solve(A, B)

# --- Impresión de resultados ---
print("Matriz de coeficientes A:")
print(A)
print("\nVector de constantes B:")
print(B)
# El vector X contendrá los valores de [x, y, z] que satisfacen el sistema.
print("\nVector de soluciones X [x, y, z]:")
print(X)

Matriz de coeficientes A:
[[2 1 1]
 [3 5 2]
 [1 2 4]]

Vector de constantes B:
[ 8 21 11]

Vector de soluciones X [x, y, z]:
[2.30434783 2.43478261 0.95652174]


##Ejercicio 5: Cálculo de determinante

In [17]:
# --- Definición de la matriz ---
# Definimos la matriz cuadrada A de la cual queremos conocer su determinante.
A = np.array([[3, -2, 1],
              [0, 5, 4],
              [2, 1, 7]])

# --- Cálculo del determinante ---
# Usamos la función det() del módulo de álgebra lineal de NumPy (linalg).
determinante_A = np.linalg.det(A)

# --- Impresión de resultados ---
print("Matriz A:")
print(A)
# Usamos una f-string para imprimir el resultado de forma clara.
print(f"\nDeterminante de A: {determinante_A}")

Matriz A:
[[ 3 -2  1]
 [ 0  5  4]
 [ 2  1  7]]

Determinante de A: 67.00000000000004


##Ejercicio 6: Producto cruz de vectores

In [18]:
# --- Definición de los vectores ---
# Definimos el vector A como un arreglo de NumPy.
A = np.array([2, 3, -1])

# Definimos el vector B.
B = np.array([1, -2, 4])

# --- Cálculo del producto cruz ---
# La función np.cross() calcula el producto cruz entre dos vectores.
# El resultado es un nuevo vector que es ortogonal (perpendicular) tanto a A como a B.
producto_cruz = np.cross(A, B)

# --- Impresión de resultados ---
print(f"Vector A: {A}")
print(f"Vector B: {B}")
print(f"\nProducto Cruz (A x B), un vector perpendicular a A y B: {producto_cruz}")

Vector A: [ 2  3 -1]
Vector B: [ 1 -2  4]

Producto Cruz (A x B), un vector perpendicular a A y B: [10 -9 -7]


##Ejercicio 7: Proyección ortogonal

In [19]:
# --- Definición de los vectores ---
# Vector V que será proyectado.
V = np.array([5, -3, 2])
# Vector U sobre el cual se proyectará V.
U = np.array([2, 1, 2])

# --- Cálculo de la proyección según la fórmula ---
# Fórmula: proy_U(V) = ( (V·U) / ||U||² ) * U

# 1. Calculamos el producto escalar (o producto punto) entre V y U.
producto_escalar = np.dot(V, U)

# 2. Calculamos la magnitud al cuadrado de U. Es más eficiente hacer U·U que sqrt(U·U)².
u_mag_cuadrada = np.dot(U, U)

# 3. Aplicamos la fórmula completa.
# El resultado de (producto_escalar / u_mag_cuadrada) es un escalar que "escala" el vector U.
proyeccion = (producto_escalar / u_mag_cuadrada) * U

# --- Impresión de resultados ---
print(f"Vector V: {V}")
print(f"Vector U: {U}")
print(f"\nProyección de V sobre U: {proyeccion}")

Vector V: [ 5 -3  2]
Vector U: [2 1 2]

Proyección de V sobre U: [2.44444444 1.22222222 2.44444444]


##Ejercicio 8: Producto escalar de proyecciones

In [20]:
# --- Definición de los vectores ---
V = np.array([3, -1, 2])
U = np.array([2, 2, -1])
W = np.array([1, 4, -2])

# --- Paso 1: Calcular la proyección de V sobre U ---
# Reutilizamos la lógica del ejercicio anterior.
proj_V_en_U = (np.dot(V, U) / np.dot(U, U)) * U

# --- Paso 2: Calcular la proyección de V sobre W ---
# Aplicamos la misma fórmula, pero ahora con los vectores V y W.
proj_V_en_W = (np.dot(V, W) / np.dot(W, W)) * W

# --- Paso 3: Calcular el producto escalar de los resultados ---
# Calculamos el producto punto entre los dos vectores de proyección que obtuvimos.
resultado_final = np.dot(proj_V_en_U, proj_V_en_W)

# --- Impresión de resultados ---
print(f"Proyección de V sobre U: {proj_V_en_U}")
print(f"Proyección de V sobre W: {proj_V_en_W}")
print(f"\nProducto escalar de las dos proyecciones: {resultado_final}")

Proyección de V sobre U: [ 0.44444444  0.44444444 -0.22222222]
Proyección de V sobre W: [-0.23809524 -0.95238095  0.47619048]

Producto escalar de las dos proyecciones: -0.6349206349206349


##Ejercicio 9: Ortogonalización de Gram-Schmidt

In [21]:
# --- Definición de los vectores originales ---
v1 = np.array([1, 1, 0])
v2 = np.array([1, 2, 1])
v3 = np.array([2, 1, 3])

# --- Función auxiliar para la proyección ---
# Definimos una función para calcular la proyección y así no repetir código.
# Esta función toma el vector a proyectar (v) y el vector sobre el que se proyecta (u).
def proyeccion(v, u):
    return (np.dot(v, u) / np.dot(u, u)) * u

# --- Proceso de Ortogonalización ---
# 1. El primer vector ortogonal (u1) es simplemente el primer vector original (v1).
u1 = v1

# 2. El segundo vector (u2) se obtiene restando a v2 su proyección sobre u1.
# Esto elimina la componente de v2 que va en la dirección de u1, dejando solo la parte perpendicular.
u2 = v2 - proyeccion(v2, u1)

# 3. El tercer vector (u3) se obtiene restando a v3 sus proyecciones sobre u1 y u2.
# Así, eliminamos las componentes en las direcciones de los dos primeros vectores ortogonales.
u3 = v3 - proyeccion(v3, u1) - proyeccion(v3, u2)

# --- Impresión de resultados ---
print("Vectores originales:")
print(f"v1 = {v1}")
print(f"v2 = {v2}")
print(f"v3 = {v3}")
print("\nConjunto ortogonal equivalente (u1, u2, u3):")
print(f"u1 = {u1}")
print(f"u2 = {u2}")
print(f"u3 = {u3}")

Vectores originales:
v1 = [1 1 0]
v2 = [1 2 1]
v3 = [2 1 3]

Conjunto ortogonal equivalente (u1, u2, u3):
u1 = [1 1 0]
u2 = [-0.5  0.5  1. ]
u3 = [ 1.33333333 -1.33333333  1.33333333]


##Ejercicio 10: Espacio nulo

In [22]:
# --- Definición de la matriz con SymPy ---
# Usamos la librería SymPy porque es excelente para cálculos algebraicos exactos,
# a diferencia de NumPy que se enfoca en cálculos numéricos (con decimales).
A = Matrix([[1, 2, 0, 3],
            [0, 1, 0, 2],
            [0, 0, 1, 1]])

# --- Cálculo del espacio nulo ---
# El método .nullspace() de un objeto Matriz de SymPy calcula directamente
# una lista de vectores que forman una base para el espacio nulo.
base_espacio_nulo = A.nullspace()

# --- Impresión de resultados ---
print("Matriz A:")
# Imprimimos la matriz de SymPy de una forma más legible.
for row in A.tolist():
    print(row)

print("\nBase para el espacio nulo de A:")
# El resultado es una lista que contiene uno o más vectores. Cada vector en esta
# lista es una solución a Av=0, y cualquier combinación lineal de ellos también lo es.
for vector in base_espacio_nulo:
    print(vector)

Matriz A:
[1, 2, 0, 3]
[0, 1, 0, 2]
[0, 0, 1, 1]

Base para el espacio nulo de A:
Matrix([[1], [-2], [-1], [1]])
